#!/bin/bash -e
source $(dirname -- "$0")/../utils.bash

if [ "$#" -ne 3 ]; then
    echo "Usage: $0 [bridge] [mtu] [localif]"
    exit 1
fi

bname=$1
mtu=$2
localif=$3

add_to_bridge ${bname} ${mtu} ${localif}
