#!/bin/sh -e

LOGDIR=./main
LOGUSER=syslog

if [ ! -e ${LOGDIR} ]; then
    mkdir -p ${LOGDIR}
    chmod 700 ${LOGDIR}
    chown -R ${LOGUSER} ${LOGDIR}
fi

exec chpst -u ${LOGUSER} \
     svlogd -tt ${LOGDIR}
