#!/bin/bash -e
source $(dirname -- "$0")/../utils.bash

if [ "$#" -ne 10 ]; then
    echo "Usage: $0 [bridge] [mtu] [container] [localif] [containerif] [ip/netmask] [mac] [overlaynet] [gwip] \"[alternate_networks]\""
fi

bname=$1
mtu=$2
container=$3
localif=$4
containerif=$5
ip=$6
mac=$7
overlaynet=$8
gwip=$9
alternate_networks=${10}

# set up NS link
link_netns ${container}

# create veth pair and add to bridge
tempif=$(bridge_veth_pair ${bname} ${mtu} ${localif})

# add remote interface to container
ip link set ${tempif} netns ${container}
ip netns exec ${container} \
   ip link set ${tempif} up \
   mtu ${mtu} name ${containerif} address ${mac}
# set IP for container
ip netns exec ${container} \
   ip addr replace ${ip} dev ${containerif}

# set up route for virtual gateway
ip netns exec ${container} \
   ip route replace to ${overlaynet} via ${gwip}


for net in $alternate_networks; do
    ip netns exec ${container} \
       ip route add $net via ${gwip} dev eth1
done
