#!/bin/bash -e
source $(dirname -- "$0")/../utils.bash

mtu=$1
localif=$2
ip=$3
alternate_networks=$4
ip_nomask=${ip:0:$(expr $(expr index $ip \/) - 1)}
# set IP for interface
ip addr replace ${ip} dev ${localif}

# bring up interface
ip link set ${localif} up mtu ${mtu}

for net in $alternate_networks; do
    ip route add $net via ${ip_nomask} dev ${localif}
done
